### ISSUE TITLE
Interested in helping

### ISSUE THREAD

**Issue by tyduptyler13** [Mineserver/mineserver2#11]
I have had a great desire to build a minecraft server and I am wondering what needs to be done to get this project going. It looks like it hasn't been touched in quite a long time.

**Comment by carlbennett** [comment]
That's a good question.

**Comment by carlbennett** [comment]
@deoxxa and @fador have better knowledge on how to answer this.

**Comment by fador** [comment]
If I remember correctly, Mineserver2 was in quite an early stage of development and never actually usable =/ I wasn't actually coding ms2 so I don't know too much about it =)

..anyway, the whole protocol has changed since then and big parts of the code must be done again..
Good thing is that now the packets are actually prefixed with the length so you can skip unknown stuff ;)

**Comment by fador** [comment]
..and I would love to see mineserver rise again =)

There are some people in [#mineserver at Freenode IRC network](http://webchat.freenode.net?channels=%23mineserver&uio=d4) who might be interested in this too..

**Comment by tyduptyler13** [comment]
Well for now I am doing some minor work on a custom client. Still playing with libraries and what needs to go into it first but I will likely have some parts of the client that will work for the server as well.

**Comment by carlbennett** [comment]
> Good thing is that now the packets are actually prefixed with the length

Yes, I love this part. It makes things 10x easier.

**Comment by carlbennett** [comment]
_Sad trombone_
